# Generated by Django 3.2.1 on 2021-05-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empadronamiento', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street',
            new_name='calle',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='dpt',
            new_name='codigo_postal',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='postal_code',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='street_no',
            new_name='no',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='person',
            new_name='persona',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='floor',
            new_name='piso',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='address',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='neighborhood',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='fname',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='lname',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='usuario',
        ),
    ]
