# Generated by Django 3.2.1 on 2021-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empadronamiento', '0005_auto_20210517_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='nombre',
            field=models.CharField(choices=[('Agronomia', 'Agronomia'), ('Almagro', 'Almagro'), ('Balvanera', 'Balvanera'), ('Barracas', 'Barracas'), ('Belgrano', 'Belgrano'), ('Boedo', 'Boedo'), ('Caballito', 'Caballito'), ('Chacarita', 'Chacarita'), ('Coghlan', 'Coghlan'), ('Colegiales', 'Colegiales'), ('Constitucion', 'Constitucion'), ('Flores', 'Flores'), ('Floresta', 'Floresta'), ('La Boca', 'La Boca'), ('La Paternal', 'La Paternal'), ('Liniers', 'Liniers'), ('Mataderos', 'Mataderos'), ('Monte Castro', 'Monte Castro'), ('Monserrat', 'Monserrat'), ('Nueva Pompeya', 'Nueva Pompeya'), ('Nuñez', 'Nuñez'), ('Palermo', 'Palermo'), ('Parque Avellaneda', 'Parque Avellaneda'), ('Parque Chacabuco', 'Parque Chacabuco'), ('Parque Chas', 'Parque Chas'), ('Parque Patricios', 'Parque Patricios'), ('Puerto Madero', 'Puerto Madero'), ('Recoleta', 'Recoleta'), ('Retiro', 'Retiro'), ('Saavedra', 'Saavedra'), ('San Cristobal', 'San Cristobal'), ('San Nicolas', 'San Nicolas'), ('San Telmo', 'San Telmo'), ('Versalles', 'Versalles'), ('Villa Crespo', 'Villa Crespo'), ('Villa Devoto', 'Villa Devoto'), ('Villa General Mitre', 'Villa General Mitre'), ('Villa Lugano', 'Villa Lugano'), ('Villa Luro', 'Villa Luro'), ('Villa Ortuzar', 'Villa Ortuzar'), ('Villa Pueyrredon', 'Villa Pueyrredon'), ('Villa Real', 'Villa Real'), ('Villa Riachuelo', 'Villa Riachuelo'), ('Villa Santa Rita', 'Villa Santa Rita'), ('Villa Soldati', 'Villa Soldati'), ('Villa Urquiza', 'Villa Urquiza'), ('Villa del Parque', 'Villa del Parque'), ('Velez Sarsfield', 'Velez Sarsfield')], max_length=50),
        ),
    ]
