# Generated by Django 3.2.4 on 2021-06-04 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empadronamiento', '0009_auto_20210604_2134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='nombre',
            new_name='barrio',
        ),
    ]
